services:
  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./lamp/data/db/var/lib/mysql:/var/lib/mysql
      - ./lamp/init:/docker-entrypoint-initdb.d
    networks:
      - lamp_network

  # Apache и PHP
  web:
    build: lamp/php
    container_name: apache_php
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./lamp/data/web/var/www/html:/var/www/html
    networks:
      - lamp_network
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ALLOWED_HOSTS: http://localhost:${HTTP_SERVER_PORT}

  # phpMyAdmin (для управления MySQL базой данных через UI)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - lamp_network
    depends_on:
      - db

networks:
  lamp_network:
    driver: bridge
